import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TextInput,
  TouchableOpacity,
  Platform,
  Alert,
  ActivityIndicator,
  KeyboardAvoidingView,
  ScrollView,
  Modal,
} from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import * as Location from 'expo-location';
import DateTimePicker from '@react-native-community/datetimepicker';
import { addTree, searchTreesByBlock } from '@/services/tree';
import { fetchAllBlocks } from '@/services/block';
import { API_BASE_URL } from '@/services/api-config';
import type { Block } from '@/services/block/types';
import type { TreeResponse } from '@/services/tree/types';

interface TreeData {
  blockId: string;
  treeNumber?: string;
  latitude: number | null;
  longitude: number | null;
  placeId?: string;
  plantedDate?: string;
  plantedYear?: string;
  age?: number;
  fertilizerType?: string;
  fertilizerQty?: string;
  lastFertilizerDate?: string;
  lastPruningDate?: string;
  lastWeedingDate?: string;
}

interface TreeFormData {
  blockId: string;
  treeNumber: string; // Auto-generated by backend
  latitude: number | null;
  longitude: number | null;
  placeId: string; // Optional - for Google Maps Place ID
  plantedDate: string;
  plantedYear: string;
  age: number; // Auto-calculated
  fertilizerType: string;
  fertilizerQty: string;
  lastFertilizerDate: string;
  lastPruningDate: string;
  lastWeedingDate: string;
}

export default function AddTreeScreen() {
  const insets = useSafeAreaInsets();
  const [loading, setLoading] = useState(false);
  const [locationLoading, setLocationLoading] = useState(false);
  const [showPlantedDatePicker, setShowPlantedDatePicker] = useState(false);
  const [plantedDateValue, setPlantedDateValue] = useState<Date>(new Date());
  
  // Block and Tree dropdown state
  const [blocks, setBlocks] = useState<Block[]>([]);
  const [trees, setTrees] = useState<TreeResponse[]>([]);
  const [isLoadingBlocks, setIsLoadingBlocks] = useState(false);
  const [isLoadingTrees, setIsLoadingTrees] = useState(false);
  const [selectedBlockId, setSelectedBlockId] = useState<string>('');
  const [selectedTreeId, setSelectedTreeId] = useState<string>('');
  
  const [formData, setFormData] = useState<TreeFormData>({
    blockId: '',
    treeNumber: '',
    latitude: null,
    longitude: null,
    placeId: '',
    plantedDate: '',
    plantedYear: '',
    age: 0,
    fertilizerType: '',
    fertilizerQty: '',
    lastFertilizerDate: '',
    lastPruningDate: '',
    lastWeedingDate: '',
  });

  // Fetch all blocks on component mount
  useEffect(() => {
    console.log('🚀 AddTreeScreen mounted - loading blocks...');
    loadBlocks();
  }, []);

  // Fetch trees when block is selected
  useEffect(() => {
    if (selectedBlockId) {
      loadTreesByBlock(selectedBlockId);
    } else {
      // Clear trees when no block is selected
      setTrees([]);
      setSelectedTreeId('');
    }
  }, [selectedBlockId]);

  // Auto-calculate age when planted date or year changes
  useEffect(() => {
    if (formData.plantedDate) {
      const plantedDate = new Date(formData.plantedDate + 'T00:00:00');
      if (!isNaN(plantedDate.getTime())) {
        const today = new Date();
        const age = Math.floor((today.getTime() - plantedDate.getTime()) / (1000 * 60 * 60 * 24 * 365.25));
        setFormData((prev) => ({ ...prev, age: age >= 0 ? age : 0 }));
      }
    } else if (formData.plantedYear) {
      const currentYear = new Date().getFullYear();
      const plantedYear = parseInt(formData.plantedYear);
      if (!isNaN(plantedYear) && plantedYear > 0) {
        const age = currentYear - plantedYear;
        setFormData((prev) => ({ ...prev, age: age >= 0 ? age : 0 }));
      }
    } else {
      setFormData((prev) => ({ ...prev, age: 0 }));
    }
  }, [formData.plantedDate, formData.plantedYear]);

  // Load all blocks from API
  const loadBlocks = async () => {
    console.log('🔄 Starting to load blocks...');
    console.log('🔍 Checking API configuration...');
    console.log('📍 Current API_BASE_URL from config:', API_BASE_URL);
    
    if (!API_BASE_URL) {
      Alert.alert('Configuration Error', 'API_BASE_URL is not configured. Check app.json');
      return;
    }
    
    setIsLoadingBlocks(true);
    try {
      const response = await fetchAllBlocks();
      console.log('📦 Block response:', JSON.stringify(response, null, 2));
      
      if (response.success && response.data) {
        console.log('✅ Blocks loaded successfully:', response.data.length, 'blocks');
        setBlocks(response.data);
      } else {
        console.log('❌ Failed to load blocks:', response.message);
        Alert.alert('Error', response.message || 'Failed to load blocks');
      }
    } catch (error) {
      console.error('💥 Error loading blocks:', error);
      Alert.alert('Error', 'Failed to load blocks. Please check console for details.');
    } finally {
      setIsLoadingBlocks(false);
      console.log('🏁 Finished loading blocks');
    }
  };

  // Load trees filtered by block ID
  const loadTreesByBlock = async (blockId: string) => {
    setIsLoadingTrees(true);
    try {
      const response = await searchTreesByBlock(blockId);
      if (response.success && response.data) {
        setTrees(response.data);
      } else {
        // Empty result is ok, just clear the list
        setTrees([]);
      }
    } catch (error) {
      console.error('Error loading trees:', error);
      setTrees([]);
    } finally {
      setIsLoadingTrees(false);
    }
  };

  // Handle block selection
  const handleBlockChange = (blockId: string) => {
    setSelectedBlockId(blockId);
    setFormData((prev) => ({ ...prev, blockId }));
    // Clear tree selection when block changes
    setSelectedTreeId('');
  };

  // Get current GPS location
  const getCurrentLocation = async () => {
    setLocationLoading(true);
    try {
      // Request location permissions
      const { status } = await Location.requestForegroundPermissionsAsync();
      if (status !== 'granted') {
        Alert.alert(
          'Permission Denied',
          'Location permission is required to set GPS coordinates.'
        );
        setLocationLoading(false);
        return;
      }

      // Get current position
      const location = await Location.getCurrentPositionAsync({
        accuracy: Location.Accuracy.High,
      });

      setFormData((prev) => ({
        ...prev,
        latitude: location.coords.latitude,
        longitude: location.coords.longitude,
      }));

      Alert.alert(
        'Location Set',
        `GPS coordinates set:\nLatitude: ${location.coords.latitude.toFixed(6)}\nLongitude: ${location.coords.longitude.toFixed(6)}`
      );
    } catch (error) {
      console.error('Error getting location:', error);
      Alert.alert('Error', 'Failed to get location. Please try again.');
    } finally {
      setLocationLoading(false);
    }
  };

  // Format date for display (YYYY-MM-DD)
  const formatDate = (date: Date): string => {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  // Format date for display (e.g., "Jan 15, 2024")
  const formatDateDisplay = (dateString: string): string => {
    if (!dateString) return '';
    const date = new Date(dateString + 'T00:00:00');
    if (isNaN(date.getTime())) return dateString;
    
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
  };

  // Handle planted date picker
  const handlePlantedDatePress = () => {
    if (formData.plantedDate) {
      const date = new Date(formData.plantedDate + 'T00:00:00');
      if (!isNaN(date.getTime())) {
        setPlantedDateValue(date);
      }
    }
    setShowPlantedDatePicker(true);
  };

  const handlePlantedDateChange = (event: any, selectedDate?: Date) => {
    if (Platform.OS === 'android') {
      setShowPlantedDatePicker(false);
      
      if (event.type === 'set' && selectedDate) {
        const formattedDate = formatDate(selectedDate);
        setFormData((prev) => {
          const updated = { ...prev, plantedDate: formattedDate };
          // Also update planted year if not set
          if (!prev.plantedYear) {
            updated.plantedYear = String(selectedDate.getFullYear());
          }
          return updated;
        });
      }
    } else {
      // iOS - handled in the modal's Done button
      if (event.type === 'set' && selectedDate) {
        setPlantedDateValue(selectedDate);
      } else if (event.type === 'dismissed') {
        setShowPlantedDatePicker(false);
      }
    }
  };

  // Show date picker for other date fields (keeping simple for now)
  const showDatePicker = (field: 'lastFertilizerDate' | 'lastPruningDate' | 'lastWeedingDate') => {
    Alert.prompt(
      'Select Date',
      'Enter date in YYYY-MM-DD format',
      [
        {
          text: 'Cancel',
          style: 'cancel',
        },
        {
          text: 'Use Today',
          onPress: () => {
            const today = formatDate(new Date());
            setFormData((prev) => ({ ...prev, [field]: today }));
          },
        },
        {
          text: 'OK',
          onPress: (date?: string) => {
            if (date && /^\d{4}-\d{2}-\d{2}$/.test(date)) {
              setFormData((prev) => ({ ...prev, [field]: date }));
            } else {
              Alert.alert('Invalid Date', 'Please enter date in YYYY-MM-DD format');
            }
          },
        },
      ],
      'plain-text',
      formData[field] || formatDate(new Date())
    );
  };

  // Validate and submit form
  const handleSubmit = async () => {
    // Validation
    if (!formData.blockId.trim()) {
      Alert.alert('Error', 'Please enter Block ID');
      return;
    }

    if (!formData.plantedDate && !formData.plantedYear) {
      Alert.alert('Error', 'Please enter either Planted Date or Planted Year');
      return;
    }

    if (formData.plantedYear && (parseInt(formData.plantedYear) < 1900 || parseInt(formData.plantedYear) > new Date().getFullYear())) {
      Alert.alert('Error', 'Please enter a valid planted year');
      return;
    }

    setLoading(true);
    try {
      // Prepare tree data for API
      const treeData: TreeData = {
        blockId: formData.blockId.trim(),
        treeNumber: formData.treeNumber || undefined, // Will be auto-generated by backend
        latitude: formData.latitude,
        longitude: formData.longitude,
        placeId: formData.placeId.trim() || undefined,
        plantedDate: formData.plantedDate || undefined,
        plantedYear: formData.plantedYear || undefined,
        age: formData.age > 0 ? formData.age : undefined,
        fertilizerType: formData.fertilizerType.trim() || undefined,
        fertilizerQty: formData.fertilizerQty.trim() || undefined,
        lastFertilizerDate: formData.lastFertilizerDate || undefined,
        lastPruningDate: formData.lastPruningDate || undefined,
        lastWeedingDate: formData.lastWeedingDate || undefined,
      };

      console.log('Submitting tree data:', treeData);
      
      const response = await addTree(treeData);

      if (response.success) {
        Alert.alert(
          'Success',
          response.message || 'Tree added successfully!',
          [
            {
              text: 'OK',
              onPress: () => router.back(),
            },
          ]
        );
      } else {
        Alert.alert('Error', response.message || 'Failed to add tree. Please try again.');
      }
    } catch (error) {
      console.error('Error submitting tree:', error);
      Alert.alert('Error', 'An unexpected error occurred. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const updateFormData = (field: keyof TreeFormData, value: string | number | null) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
    >
      <LinearGradient
        colors={['#1B5E20', '#2E7D32', '#388E3C']}
        style={[styles.headerGradient, { paddingTop: insets.top + 20 }]}
      >
        <View style={styles.headerContent}>
          <TouchableOpacity
            style={styles.backButton}
            onPress={() => router.back()}
            activeOpacity={0.8}
          >
            <Ionicons name="arrow-back" size={24} color="#FFFFFF" />
          </TouchableOpacity>
          <View style={styles.logoContainer}>
            <View style={styles.logoCircle}>
              <Ionicons name="add-circle" size={40} color="#FFFFFF" />
            </View>
          </View>
          <Text style={styles.headerTitle}>Add New Tree</Text>
          <Text style={styles.headerSubtitle}>Register oil palm tree information</Text>
        </View>
      </LinearGradient>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 20 }]}
        showsVerticalScrollIndicator={false}
        keyboardShouldPersistTaps="handled"
      >
        <View style={styles.formCard}>
          {/* Block ID */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Basic Information</Text>
            
            <View style={styles.inputContainer}>
              <View style={styles.labelRow}>
                <Text style={styles.label}>Block ID *</Text>
                {blocks.length === 0 && !isLoadingBlocks && (
                  <TouchableOpacity onPress={loadBlocks} style={styles.retryButton}>
                    <Ionicons name="refresh" size={16} color="#2E7D32" />
                    <Text style={styles.retryText}>Retry</Text>
                  </TouchableOpacity>
                )}
              </View>
              <View style={styles.pickerWrapper}>
                <Ionicons name="grid-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                {isLoadingBlocks ? (
                  <View style={styles.pickerLoadingContainer}>
                    <ActivityIndicator size="small" color="#2E7D32" />
                    <Text style={styles.pickerLoadingText}>Loading blocks...</Text>
                  </View>
                ) : (
                  <Picker
                    selectedValue={selectedBlockId}
                    onValueChange={handleBlockChange}
                    style={styles.picker}
                    enabled={blocks.length > 0}
                  >
                    <Picker.Item label="Select a Block" value="" />
                    {blocks.map((block) => (
                      <Picker.Item
                        key={block.id}
                        label={`${block.id} - ${block.name}`}
                        value={block.id}

                      />
                    ))}
                  </Picker>
                )}
              </View>
              {blocks.length === 0 && !isLoadingBlocks && (
                <Text style={styles.helperText}>No blocks found. Check console logs or tap Retry.</Text>
              )}
              {blocks.length > 0 && (
                <Text style={styles.helperText}>{blocks.length} block(s) available</Text>
              )}
            </View>

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Tree Number</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="keypad-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={[styles.input, styles.disabledInput]}
                  placeholder="Auto-generated"
                  placeholderTextColor="#9E9E9E"
                  value={formData.treeNumber}
                  editable={false}
                />
                <Ionicons name="lock-closed" size={16} color="#9E9E9E" />
              </View>
              <Text style={styles.helperText}>Tree number will be auto-generated in database</Text>
            </View>

            {/* Tree Reference Dropdown (Optional - for viewing existing trees) */}
            {selectedBlockId && (
              <View style={styles.inputContainer}>
                <Text style={styles.label}>Existing Trees in Block (Reference Only)</Text>
                <View style={styles.pickerWrapper}>
                  <Ionicons name="list-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                  {isLoadingTrees ? (
                    <View style={styles.pickerLoadingContainer}>
                      <ActivityIndicator size="small" color="#2E7D32" />
                      <Text style={styles.pickerLoadingText}>Loading trees...</Text>
                    </View>
                  ) : (
                    <Picker
                      selectedValue={selectedTreeId}
                      onValueChange={(value) => setSelectedTreeId(value)}
                      style={styles.picker}
                      enabled={trees.length > 0}
                    >
                      <Picker.Item label="View existing trees in this block" value="" />
                      {trees.map((tree) => (
                        <Picker.Item
                          key={tree.treeId || tree.treeNumber}
                          label={`Tree ${tree.treeNumber || tree.treeId} - Age: ${tree.age || 'N/A'}`}
                          value={tree.treeId || tree.treeNumber || ''}
                        />
                      ))}
                    </Picker>
                  )}
                </View>
                {trees.length === 0 && !isLoadingTrees && (
                  <Text style={styles.helperText}>No trees found in this block. You&apos;ll add the first one!</Text>
                )}
                {trees.length > 0 && (
                  <Text style={styles.helperText}>
                    {trees.length} tree{trees.length > 1 ? 's' : ''} already in this block
                  </Text>
                )}
              </View>
            )}
          </View>

          {/* GPS Location */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Location (Optional)</Text>
            
            <TouchableOpacity
              style={styles.locationButton}
              onPress={getCurrentLocation}
              activeOpacity={0.8}
              disabled={locationLoading}
            >
              <LinearGradient
                colors={['#4CAF50', '#66BB6A']}
                start={{ x: 0, y: 0 }}
                end={{ x: 1, y: 0 }}
                style={styles.locationButtonGradient}
              >
                {locationLoading ? (
                  <ActivityIndicator color="#FFFFFF" />
                ) : (
                  <>
                    <Ionicons name="location" size={20} color="#FFFFFF" />
                    <Text style={styles.locationButtonText}>Set GPS Location</Text>
                  </>
                )}
              </LinearGradient>
            </TouchableOpacity>

            {formData.latitude !== null && formData.longitude !== null && (
              <View style={styles.locationInfo}>
                <View style={styles.locationRow}>
                  <Ionicons name="pin" size={16} color="#4CAF50" />
                  <Text style={styles.locationText}>
                    Lat: {formData.latitude.toFixed(6)}
                  </Text>
                </View>
                <View style={styles.locationRow}>
                  <Ionicons name="pin" size={16} color="#4CAF50" />
                  <Text style={styles.locationText}>
                    Lng: {formData.longitude.toFixed(6)}
                  </Text>
                </View>
              </View>
            )}

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Google Place ID (Optional)</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="map-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter Place ID"
                  placeholderTextColor="#9E9E9E"
                  value={formData.placeId}
                  onChangeText={(value) => updateFormData('placeId', value)}
                />
              </View>
              <Text style={styles.helperText}>Optional: Google Maps Place ID for location reference</Text>
            </View>
          </View>

          {/* Planting Information */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Planting Information</Text>
            
            <View style={styles.inputContainer}>
              <Text style={styles.label}>Planted Date</Text>
              <TouchableOpacity
                style={styles.dateInput}
                onPress={handlePlantedDatePress}
                activeOpacity={0.8}
              >
                <Ionicons name="calendar-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <Text style={[styles.dateText, !formData.plantedDate && styles.placeholderText]}>
                  {formData.plantedDate ? formatDateDisplay(formData.plantedDate) : 'Tap to select date from calendar'}
                </Text>
                <Ionicons name="chevron-forward" size={20} color="#9E9E9E" />
              </TouchableOpacity>
            </View>
            
            {/* Date Picker Modal for Planted Date */}
            {showPlantedDatePicker && (
              Platform.OS === 'ios' ? (
                <Modal
                  visible={showPlantedDatePicker}
                  transparent
                  animationType="slide"
                  onRequestClose={() => setShowPlantedDatePicker(false)}
                >
                  <View style={styles.datePickerModal}>
                    <View style={styles.datePickerContainer}>
                      <View style={styles.datePickerHeader}>
                        <TouchableOpacity
                          onPress={() => setShowPlantedDatePicker(false)}
                          style={styles.datePickerCancelButton}
                        >
                          <Text style={styles.datePickerCancelText}>Cancel</Text>
                        </TouchableOpacity>
                        <Text style={styles.datePickerTitle}>Select Planted Date</Text>
                        <TouchableOpacity
                          onPress={() => {
                            const formattedDate = formatDate(plantedDateValue);
                            setFormData((prev) => ({
                              ...prev,
                              plantedDate: formattedDate,
                              plantedYear: prev.plantedYear || String(plantedDateValue.getFullYear()),
                            }));
                            setShowPlantedDatePicker(false);
                          }}
                          style={styles.datePickerDoneButton}
                        >
                          <Text style={styles.datePickerDoneText}>Done</Text>
                        </TouchableOpacity>
                      </View>
                      <DateTimePicker
                        value={plantedDateValue}
                        mode="date"
                        display="spinner"
                        onChange={(event, date) => {
                          if (event.type === 'set' && date) {
                            setPlantedDateValue(date);
                          }
                        }}
                        maximumDate={new Date()}
                        style={styles.datePicker}
                      />
                    </View>
                  </View>
                </Modal>
              ) : (
                <DateTimePicker
                  value={plantedDateValue}
                  mode="date"
                  display="default"
                  onChange={handlePlantedDateChange}
                  maximumDate={new Date()}
                />
              )
            )}

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Planted Year</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="calendar-number-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="YYYY (e.g., 2020)"
                  placeholderTextColor="#9E9E9E"
                  value={formData.plantedYear}
                  onChangeText={(value) => updateFormData('plantedYear', value.replace(/\D/g, '').slice(0, 4))}
                  keyboardType="number-pad"
                  maxLength={4}
                />
              </View>
            </View>

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Tree Age</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="time-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={[styles.input, styles.disabledInput]}
                  placeholder="Auto-calculated"
                  placeholderTextColor="#9E9E9E"
                  value={formData.age > 0 ? `${formData.age} years` : ''}
                  editable={false}
                />
                <Ionicons name="lock-closed" size={16} color="#9E9E9E" />
              </View>
              <Text style={styles.helperText}>Automatically calculated from planted year</Text>
            </View>
          </View>

          {/* Fertilizer Information */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Fertilizer Information</Text>
            
            <View style={styles.inputContainer}>
              <Text style={styles.label}>Fertilizer Type</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="leaf-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter fertilizer type"
                  placeholderTextColor="#9E9E9E"
                  value={formData.fertilizerType}
                  onChangeText={(value) => updateFormData('fertilizerType', value)}
                />
              </View>
            </View>

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Fertilizer Quantity</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="scale-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter quantity (kg)"
                  placeholderTextColor="#9E9E9E"
                  value={formData.fertilizerQty}
                  onChangeText={(value) => updateFormData('fertilizerQty', value)}
                  keyboardType="decimal-pad"
                />
              </View>
            </View>

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Last Fertilizer Date</Text>
              <TouchableOpacity
                style={styles.dateInput}
                onPress={() => showDatePicker('lastFertilizerDate')}
                activeOpacity={0.8}
              >
                <Ionicons name="calendar-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <Text style={[styles.dateText, !formData.lastFertilizerDate && styles.placeholderText]}>
                  {formData.lastFertilizerDate || 'Select Last Fertilizer Date'}
                </Text>
                <Ionicons name="chevron-forward" size={20} color="#9E9E9E" />
              </TouchableOpacity>
            </View>
          </View>

          {/* Maintenance Information */}
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Maintenance Information</Text>
            
            <View style={styles.inputContainer}>
              <Text style={styles.label}>Last Pruning Date</Text>
              <TouchableOpacity
                style={styles.dateInput}
                onPress={() => showDatePicker('lastPruningDate')}
                activeOpacity={0.8}
              >
                <Ionicons name="calendar-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <Text style={[styles.dateText, !formData.lastPruningDate && styles.placeholderText]}>
                  {formData.lastPruningDate || 'Select Last Pruning Date'}
                </Text>
                <Ionicons name="chevron-forward" size={20} color="#9E9E9E" />
              </TouchableOpacity>
            </View>

            <View style={styles.inputContainer}>
              <Text style={styles.label}>Last Weeding Date</Text>
              <TouchableOpacity
                style={styles.dateInput}
                onPress={() => showDatePicker('lastWeedingDate')}
                activeOpacity={0.8}
              >
                <Ionicons name="calendar-outline" size={20} color="#2E7D32" style={styles.inputIcon} />
                <Text style={[styles.dateText, !formData.lastWeedingDate && styles.placeholderText]}>
                  {formData.lastWeedingDate || 'Select Last Weeding Date'}
                </Text>
                <Ionicons name="chevron-forward" size={20} color="#9E9E9E" />
              </TouchableOpacity>
            </View>
          </View>

          {/* Submit Button */}
          <TouchableOpacity
            style={[styles.submitButton, loading && styles.submitButtonDisabled]}
            onPress={handleSubmit}
            activeOpacity={0.8}
            disabled={loading}
          >
            <LinearGradient
              colors={['#4CAF50', '#66BB6A']}
              start={{ x: 0, y: 0 }}
              end={{ x: 1, y: 0 }}
              style={styles.buttonGradient}
            >
              {loading ? (
                <ActivityIndicator color="#FFFFFF" />
              ) : (
                <>
                  <Text style={styles.submitButtonText}>Save Tree</Text>
                  <Ionicons name="checkmark-circle" size={20} color="#FFFFFF" style={{ marginLeft: 8 }} />
                </>
              )}
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FBF7',
  },
  headerGradient: {
    paddingBottom: 40,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  headerContent: {
    alignItems: 'center',
    paddingHorizontal: 32,
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    left: 32,
    top: 0,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1,
  },
  logoContainer: {
    marginBottom: 16,
  },
  logoCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 8,
    textAlign: 'center',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#FFFFFF',
    opacity: 0.9,
    textAlign: 'center',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  scrollView: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
      },
      android: {
        elevation: 8,
      },
    }),
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2E7D32',
    marginBottom: 16,
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  inputContainer: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#424242',
    marginBottom: 8,
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 16,
  },
  inputIcon: {
    marginRight: 12,
  },
  input: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: '#212121',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  disabledInput: {
    backgroundColor: '#FAFAFA',
    color: '#9E9E9E',
  },
  helperText: {
    fontSize: 12,
    color: '#757575',
    marginTop: 4,
    fontStyle: 'italic',
  },
  locationButton: {
    borderRadius: 12,
    overflow: 'hidden',
    marginBottom: 12,
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
      },
      android: {
        elevation: 4,
      },
    }),
  },
  locationButtonGradient: {
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  locationButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  locationInfo: {
    backgroundColor: '#E8F5E9',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  locationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  locationText: {
    fontSize: 14,
    color: '#2E7D32',
    marginLeft: 8,
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  dateInput: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  dateText: {
    flex: 1,
    fontSize: 16,
    color: '#212121',
    marginLeft: 12,
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  placeholderText: {
    color: '#9E9E9E',
  },
  submitButton: {
    borderRadius: 16,
    overflow: 'hidden',
    marginTop: 8,
    ...Platform.select({
      ios: {
        shadowColor: '#4CAF50',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
      },
      android: {
        elevation: 6,
      },
    }),
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  buttonGradient: {
    paddingVertical: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  datePickerModal: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  datePickerContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 20,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
      },
      android: {
        elevation: 10,
      },
    }),
  },
  datePickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  datePickerCancelButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  datePickerCancelText: {
    color: '#757575',
    fontSize: 16,
    fontWeight: '500',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  datePickerTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#212121',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  datePickerDoneButton: {
    paddingVertical: 8,
    paddingHorizontal: 4,
  },
  datePickerDoneText: {
    color: '#2E7D32',
    fontSize: 16,
    fontWeight: '600',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif-medium' },
    }),
  },
  datePicker: {
    width: '100%',
    height: 200,
  },
  // Picker styles
  pickerWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    paddingLeft: 16,
    overflow: 'hidden',
  },
  picker: {
    flex: 1,
    height: 50,
    ...Platform.select({
      ios: {
        marginLeft: -8,
      },
      android: {
        marginLeft: 0,
      },
    }),
  },
  pickerLoadingContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingRight: 16,
  },
  pickerLoadingText: {
    marginLeft: 8,
    fontSize: 14,
    color: '#757575',
    ...Platform.select({
      ios: { fontFamily: 'System' },
      android: { fontFamily: 'sans-serif' },
    }),
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  retryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  retryText: {
    fontSize: 12,
    color: '#2E7D32',
    fontWeight: '600',
  },
});

