export interface TreeFormData {
  blockId: string;
  treeNumber: string; // Auto-generated by backend
  latitude: number | null;
  longitude: number | null;
  placeId: string; // Optional - for Google Maps Place ID
  plantedDate: string;
  age: number; // Auto-calculated
  fertilizerType: string;
  fertilizerQty: string;
  lastFertilizerDate: string;
  lastPruningDate: string;
  lastWeedingDate: string;
}

export interface TreeData {
  blockId: string;
  treeNumber?: string; // Auto-generated by backend
  latitude?: number | null;
  longitude?: number | null;
  placeId?: string; // Optional - Google Maps Place ID
  plantedDate?: string;
  age?: number; // Auto-calculated
  fertilizerType?: string;
  fertilizerQty?: string;
  lastFertilizerDate?: string;
  lastPruningDate?: string;
  lastWeedingDate?: string;
}

export interface TreeResponse {
  treeId?: string;
  treeNumber?: string;
  blockId?: string;
  plantedDate?: string;
  age?: number;
  [key: string]: any;
}
