/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/addTree/add-tree`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/qrscan/qr-scan`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/register/register`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/searchTree/search-tree`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/startedUp`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/predictBunch/predictbunch`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/addTree/add-tree`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/login/login`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/qrscan/qr-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/register/register`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/searchTree/search-tree`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/startedUp`; params?: Router.UnknownOutputParams; } | { pathname: `/Screens/predictBunch/predictbunch`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/modal${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/Screens/addTree/add-tree${`?${string}` | `#${string}` | ''}` | `/Screens/home/home${`?${string}` | `#${string}` | ''}` | `/Screens/login/login${`?${string}` | `#${string}` | ''}` | `/Screens/qrscan/qr-scan${`?${string}` | `#${string}` | ''}` | `/Screens/register/register${`?${string}` | `#${string}` | ''}` | `/Screens/searchTree/search-tree${`?${string}` | `#${string}` | ''}` | `/Screens/startedUp${`?${string}` | `#${string}` | ''}` | `/Screens/predictBunch/predictbunch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/modal` | `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/addTree/add-tree`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/login/login`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/qrscan/qr-scan`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/register/register`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/searchTree/search-tree`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/startedUp`; params?: Router.UnknownInputParams; } | { pathname: `/Screens/predictBunch/predictbunch`; params?: Router.UnknownInputParams; };
    }
  }
}
